name: Deploy

on:
    push:
        branches: ["**"]

jobs:
    deploy_job:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.x.x'
            - run: dotnet build RollUp
            - run: dotnet test RollUp
            - run: |
                dotnet nuget add source \
                    --username Ross9519 \
                    --password ${{secrets.TOKEN}} \
                    --store-password-in-clear-text \
                    --name github "https://nuget.pkg.github.com/Ross9519/index.json"

                dotnet nuget push "RollUp/RollUp/bin/Release/RollUp.1.0.${{github.run_number}}.nupkg" \
                    --api-key ${{secrets.TOKEN}} \
                    --source "github"